# -*- coding: utf-8 -*-
"""AIChat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f864ED5P1LGv4XCuGMVrV73j6Gh3ewK6
"""

! pip install -q openai
! pip install -q gradio

import openai
import gradio

openai.api_key = "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"

messages = [{"role": "system", "content": "You are a smart and witty personal assistant with knowledge of all things."}]

from openai.api_resources import model
def CustomChatGPT(user_input):
    messages.append({"role": "user", "content": user_input})
    response = openai.ChatCompletion.create(
        model = "gpt-3.5-turbo",
        messages = messages
    )
    ChatGPT_reply = response["choices"][0]["message"]["content"]
    messages.append({"role": "assistant", "content": ChatGPT_reply})
    return ChatGPT_reply

interface = gradio.Interface(fn=CustomChatGPT, inputs="text", outputs="text", title = "AI Human")

interface.launch(share=True)